before_install:
 - "bundle install"
 - "export DISPLAY=:99.0"
 - "export PATH=$PATH:$PWD/drivers"
 - "chmod 777 $PWD/drivers/chromedriver"
 - "echo $PATH"
 - "sh -e /etc/init.d/xvfb start"

language: ruby
rvm:
 - "2.4"


script: ruby flight.rb
#watch -n 300 ruby flight.rb